version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=e_commerce_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=Admin
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=e_commerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d e_commerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: